### ISSUE TITLE
Bundle Editor for non placement (lxd) failing to deploy to machines

### ISSUE THREAD

**Issue by adam-stokes** [Ubuntu-Solutions-Engineering/bundle-placement#18]
Im guessing the bundle may be incomplete, for example, I selected the 'apace-hadoop-spark' bundle from the bigdata package and once I hit deploy it spits out this bundle:

```
machines: {}
relations:
- - spark
  - plugin
- - plugin
  - yarn-master
- - plugin
  - hdfs-master
- - yarn-master
  - hdfs-master
- - compute-slave:nodemanager
  - yarn-master:nodemanager
- - compute-slave:datanode
  - hdfs-master:datanode
- - secondary-namenode
  - hdfs-master
series: trusty
services:
  compute-slave:
    charm: cs:trusty/apache-hadoop-compute-slave-9
    num_units: 3
    options: {}
  hdfs-master:
    charm: cs:trusty/apache-hadoop-hdfs-master-9
    num_units: 1
    options: {}
  plugin:
    charm: cs:trusty/apache-hadoop-plugin-10
    num_units: 1
    options: {}
  secondary-namenode:
    charm: cs:trusty/apache-hadoop-hdfs-secondary-7
    num_units: 1
    options: {}
  spark:
    charm: cs:trusty/apache-spark-6
    num_units: 1
    options: {}
  yarn-master:
    charm: cs:trusty/apache-hadoop-yarn-master-7
    num_units: 1
    options: {}

```

And `juju status` reports:

```
[Services]         
NAME               STATUS  EXPOSED CHARM                                    
compute-slave      unknown false   cs:trusty/apache-hadoop-compute-slave-9  
hdfs-master        unknown false   cs:trusty/apache-hadoop-hdfs-master-9    
plugin                     false   cs:trusty/apache-hadoop-plugin-10        
secondary-namenode unknown false   cs:trusty/apache-hadoop-hdfs-secondary-7 
spark              unknown false   cs:trusty/apache-spark-6                 
yarn-master        unknown false   cs:trusty/apache-hadoop-yarn-master-7    

[Relations]   
SERVICE1      SERVICE2           RELATION        TYPE        
compute-slave hdfs-master        datanode        regular     
compute-slave hdfs-master        datanode        regular     
compute-slave yarn-master        nodemanager     regular     
compute-slave yarn-master        nodemanager     regular     
hdfs-master   plugin             namenode        regular     
hdfs-master   plugin             namenode        regular     
hdfs-master   secondary-namenode secondary       regular     
hdfs-master   secondary-namenode secondary       regular     
hdfs-master   yarn-master        namenode        regular     
hdfs-master   yarn-master        namenode        regular     
plugin        spark              hadoop-plugin   regular     
plugin        yarn-master        resourcemanager regular     
plugin        yarn-master        resourcemanager regular     
spark         plugin             hadoop-plugin   subordinate 

[Units] 
ID      WORKLOAD-STATUS JUJU-STATUS VERSION MACHINE PORTS PUBLIC-ADDRESS MESSAGE 

[Machines] 
ID         STATE DNS INS-ID SERIES AZ 
```

So the services are added and relations set but no LXD containers are ever created.

Though looking at the juju debug output this may be an issue with today's build of juju :cry: 

```
2016-03-17 01:29:08 ERROR cmd supercommand.go:448 cannot deploy bundle: cannot add unit for service "compute-slave": cannot add unit 1/1 to service "compute-slave": cannot add unit to service "compute-slave": Get https://10.0.3.1:8443/1.0/profiles: Unable to connect to: 10.0.3.1:8443
```

Ill keep investigating but just a heads up
